spring.application.name=fare-payment-service
server.port=${SERVER_PORT:8083}

spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/fare_payment_db}
spring.data.mongodb.auto-index-creation=true

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

ride.service.base-url=${RIDE_SERVICE_BASE_URL:http://localhost:8082}

fare.base-fare=${BASE_FARE:100.00}
fare.per-km-rate=${PER_KM_RATE:80.00}
fare.per-minute-rate=${PER_MINUTE_RATE:10.00}
