spring.application.name=account-service

server.port=${SERVER_PORT:8080}

spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/account_db}

spring.data.mongodb.auto-index-creation=true

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}