spring.application.name=ride-service

server.port=${SERVER_PORT:8082}

spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/ride_db}
spring.data.mongodb.auto-index-creation=true

# =========================================================
# JWT CONFIGURATION
# Must be the SAME secret used by Account Service
# =========================================================
app.jwt.secret=${RIDELINK_JWT_SECRET:RideLinkDemoSecretKeyForJwtSigningMustBeLongEnough123}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

# =========================================================
# DRIVER SERVICE
# =========================================================
driver.service.base-url=${DRIVER_SERVICE_BASE_URL:http://localhost:8081}
driver.service.internal-key=${DRIVER_SERVICE_INTERNAL_KEY:}